version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:10.4.24-MariaDB'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
        - '3305'

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
